### ISSUE TITLE
Zerar problemas indicados pelo Checkstyle e PMD - 2 horas

### ISSUE THREAD

**Issue by eniomoura** [eniomoura/cs-2019-01#17]
Ainda existem alguns problemas indicados pelo Checkstyle e pelo PMD. Alguns não possuem solução óbvia. Preciso de ajuda para zerar esses problemas.

**Comment by eniomoura** [comment]
@kyriosdata Efetuei a maior parte das correções encontradas pelo Checkstyle e PMD porém alguns números ainda estão sendo apontados pelo Checkstyle como magic numbers, mesmo sendo finais. Números retornados por funções também estão sendo considerados magic numbers, porém o PMD exige que o retorno da função seja feito sem variáveis intermediárias.
Ainda sobre o PMD, como evitar o problema de DU em variáveis auxiliares dos algoritmos?

**Comment by eniomoura** [comment]
@kyriosdata Outro problema que estou tendo é a regra de CyclomaticComplexity para a classe dos algoritmos. Estou utilizando apenas os métodos necessários da classe, com implementação próxima à requisitada inicialmente. Faz sentido refatorá-la para remover esse erro? Como?

**Comment by kyriosdata** [comment]
Sobre a complexidade ciclomática supostamente alta da classe com a implementação dos algoritmos. Ocorrerá com qualquer classe semelhante, ao contrário desta classe, contudo, deve ser verificado, em situações futuras, se a coesão não é prejudicada, o que não é neste caso.

**Comment by eniomoura** [comment]
@kyriosdata Certo. E sobre os problemas de Magic Numbers e DU descritos acima?

**Comment by kyriosdata** [comment]
Se forem falsos positivos, ou seja, alerme falso do PMD, ignore. Caso contrário, você tem que tratar. Teremos que observar caso por caso, neste sentido. O mesmo vale para Magic Numbers, algumas expressões usam várias constantes, o que é natural, contudo, usar 1 em vez de JANEIRO e 2 em vez de FEVEREIRO, por exemplo, é um equívoco.

**Comment by eniomoura** [comment]
Avaliando os casos, os DU encontrados são causados por loops 'while' potencialmente não tendo sua condição satisfeita, fazendo com que a variável seja indefinida - ao fim do escopo da função - antes de ser utilizada.

Os casos de erro com Magic Number encontrados são todos relacionados a acessos de índices para os algoritmos de CPF, e confirmados com o professor que não é necessário corrigir esses erros.
