### ISSUE TITLE
Conformidade - Javascript - 30 minutos

### ISSUE THREAD

**Issue by kyriosdata** [eniomoura/cs-2019-01#4]
Remova o arquivo index.html e as funções getView e addView. Agora temos os testes de unidade. Caso queira manter tais arquivos, então se trata de uso específico das fuções requisitadas. Coloque getView e addView em arquivo próprio (isolado das funções). Este novo arquivo e o arquivo index.html, ambos, estariam no diretório "gui", por exemplo. Seria uma organização melhor.

**Comment by eniomoura** [comment]
Issue resolvido como parte da refatoração.

**Comment by eniomoura** [comment]
Refatoração foi feita em java - problema foi identificado em Javascript.

**Comment by eniomoura** [comment]
Refatoração feita em javascript na branch mudançasJavascript que será evenualmente unida com a master.
