### ISSUE TITLE
Não lance Error - 30 minutos

### ISSUE THREAD

**Issue by kyriosdata** [eniomoura/cs-2019-01#8]
Na linha 136, Exercicios.java, transcrita abaixo,

```java
        throw new Error("Argumento Inválido");
```

gera-se a execeção Error, o que NÃO deve ocorrer. Sua aplicação deve fazer uso de tipo de exceção específico, possivelmente estendendo RuntimeException como IllegalArgumentException. Caso não haja exceção (tipo) adequado, então você deve criar classe própria para refletir melhor a semântica da sua aplicação.

**Comment by kyriosdata** [comment]
Observe que o comentário em #6 também se aplica ao código em Java. Ou seja, há esforço significativo de refatoração aqui.

**Comment by eniomoura** [comment]
Issue resolvido em Java como parte da refatoração.

**Comment by eniomoura** [comment]
@kyriosdata O problema se aplica também a Javascript? Pelo que entendi, em Javascript é padrão lançar diretamente o objeto contendo informação do erro, invés de uma classe padronizada.
Nesse caso, a string lançada pode ser o suficiente para dar informações sobre o erro.

**Comment by kyriosdata** [comment]
Observe que não há diferença aqui. Estamos falando da legibilidade do código, do significado dele. Ou seja, em vez de usar Error ou algo semelhante, como é comum encontrar em código JavaScript, use uma classe específica. É por este motivo que se pode estender a classe Error em JavaScript, conforme comentado [aqui](https://javascript.info/custom-errors).

**Comment by eniomoura** [comment]
Certo, o tipo dos erros será também mudado em Javascript então.

**Comment by eniomoura** [comment]
Tipo dos erros relacionados a parâmetros inválidos foi alterado para RangeError em javascript e IllegalArgumentException em java.
