### ISSUE TITLE
Legibilidade

### ISSUE THREAD

**Issue by kyriosdata** [eniomoura/cs-2019-01#9]
A linha `if (1 <= n) {` deve ser substituída, por uma questão de legibilidade, por `if (n >= 1) {`. Observe que esta ordem da condição se repete em muitas outras implementações. Faça os ajustes correspondentes.

**Comment by eniomoura** [comment]
Utilizei o padrão do enunciado para facilitar a comparação do algoritmo do enunciado com o algoritmo implementado. Porém, se considera mesmo necessário, farei a alteração.
Ainda acho interessante o uso de linhas como `if (100 <= cdu && cdu <= 999) {` porém, pois dão uma ideia de 'cdu está entre 100 e 999', que contribui para a legibilidade.

**Comment by kyriosdata** [comment]
Legibilidade nao interfere na funcao. O if e necessario. A questao e a
forma.

A sequencia natural para muitos e algo como cdu >= 100 & cdu <= 999.

Fabio

Em sex, 10 de mai de 2019 01:03, Enio Moura <notifications@github.com
escreveu:

**Comment by eniomoura** [comment]
Issue resolvido como parte da refatoração.
